spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_directory?useSSL=false&serverTimezone=UTC
    username: root
    password: admin

security:
  oauth2:
    client:
      client-id: car-rental-client
      client-secret: car-rental-secret
